### ISSUE TITLE
Game kodas arba link'as į repository

### ISSUE THREAD

**Issue by Paukal** [augisii/Augustas-J.-IIID-Blender#1]
Reiktų arba pridėti žaidimo, kuriame naudosi sukurtus modelius kodą arba į šią repositoriją arba pridėti link'ą repositorijos, kurioje tas kodas jau yra sukeltas. Jeigu bus naudojamas kažkoks external game'as, tai įkelti daugiau info apie tą žaidimą. Iš principo reikia daugiau informacijos apie aplinką kurioje tavo kurti modeliai bus naudojami.

**Comment by augisii** [comment]
Sveiki, taigi yra prideta unity aplinka zaidimo kur yra modelis.

**Comment by Paukal** [comment]
Nepamačiau pradžioj. Tada viskas tvarkoje.
